stages:
  - build
  - test_math
  - deploy


deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  tags:
    - my-runner
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
